#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=10
STOP=15
 
start() {
	echo start
  # commands to launch application
	opkg update
	opkg install python-light -d ram
	opkg install python-pip -d ram
	python /tmp/usr/bin/pip install jinja2
	cd /root/g8keepr
	git pull
	git merge
	opkg install nmap -d ram
	python /tmp/usr/bin/pip install python-nmap
}
 
stop() {          
	echo stop
  # commands to kill application 
}
